name: Deploy to S3

on:
  push:
    branches:
      - main  # Adjust if using a different branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2  # Adjust to your AWS region

      - name: Deploy to S3 with correct MIME types
        run: |
          aws s3 sync src/ s3://clever-technical-writing.com --delete
          aws s3 cp s3://clever-technical-writing.com s3://clever-technical-writing.com --recursive --exclude "*" --include "*.js" --content-type "application/javascript"
          aws s3 cp s3://clever-technical-writing.com s3://clever-technical-writing.com --recursive --exclude "*" --include "*.css" --content-type "text/css"

      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
